[package]
name = "validation_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr = "0.4"
rand = "0.8"
statrs = "0.16"
fast-math = "0.1"
itertools-num = "0.1"
interp = "1.0"